services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"

  backend:
      build: ./backend
      container_name: backend-container  # Unique name for backend service
      ports:
        - "8000:8000"  # Expose backend app on a separate port
      links:
        - db:db  
      environment:
        - DJANGO_ALLOWED_HOSTS=backend-container, localhost, host.docker.internal
        - DB_HOST=db  # Ensure DB_HOST is set to db (the service name for PostgreSQL)
        - DB_PORT=5432
        - DB_NAME=notesdb
        - DB_USER=admin
        - DB_PASSWORD=password123
      depends_on:
        - db  # Ensure that the backend service depends on db service

  frontend:
    build: ./frontend
    container_name: react-container
    ports:
      - "8084:80"  # Expose React app on port 8080
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1  # Connect to backend using service name